dist: trusty
sudo: false

language: c
compiler:
  - gcc

env:
  - MRUBY_VERSION=master
  - MRUBY_VERSION=1.4.1
  - MRUBY_VERSION=1.3.0

before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y --no-install-recommends bison git rake
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - git checkout $MRUBY_VERSION
  - cp -pf ../mruby-schash/.travis_build_config.rb build_config.rb
script:
  - make test
